version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: credit_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A credit_project worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
